USE [MicroBeard]
GO
/****** Object:  Table [dbo].[Collaborator]    Script Date: 30/10/2022 21:22:43 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Collaborator](
	[Code] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](100) NOT NULL,
	[CPF] [varchar](11) NULL,
	[Email] [varchar](80) NULL,
	[Password] [varchar](128) NULL,
	[PasswordSaltGUID] [varchar](36) NULL,
	[BirthDate] [datetime2](7) NULL,
	[Phone] [varchar](15) NULL,
	[Function] [varchar](100) NULL,
	[Salary] [decimal](9, 2) NULL,
	[Commision] [decimal](9, 2) NULL,
	[CreateDate] [datetime2](7) NULL,
	[CreatorCode] [int] NULL,
	[UpdateDate] [datetime2](7) NULL,
	[UpdaterCode] [int] NULL,
	[DesactivationDate] [datetime2](7) NULL,
	[DesactivatorCode] [int] NULL,
	[Desactivated] [bit] NULL,
	[Token] [varchar](500) NULL,
	[IsAdmin] [bit] NULL,
 CONSTRAINT [PK_Collaborator] PRIMARY KEY CLUSTERED 
(
	[Code] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 10, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IDX_COLLABORATOR_CPF]    Script Date: 30/10/2022 21:22:44 ******/
CREATE UNIQUE NONCLUSTERED INDEX [IDX_COLLABORATOR_CPF] ON [dbo].[Collaborator]
(
	[CPF] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IDX_COLLABORATOR_EMAIL]    Script Date: 30/10/2022 21:22:44 ******/
CREATE UNIQUE NONCLUSTERED INDEX [IDX_COLLABORATOR_EMAIL] ON [dbo].[Collaborator]
(
	[Email] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IDX_COLLABORATOR_TOKEN]    Script Date: 30/10/2022 21:22:44 ******/
CREATE NONCLUSTERED INDEX [IDX_COLLABORATOR_TOKEN] ON [dbo].[Collaborator]
(
	[Token] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
