USE [master]
GO
/****** Object:  Database [MicroBeard]    Script Date: 16/10/2022 13:12:19 ******/
CREATE DATABASE [MicroBeard]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MicroBeard', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\MicroBeard.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'MicroBeard_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\MicroBeard_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [MicroBeard] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MicroBeard].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [MicroBeard] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [MicroBeard] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [MicroBeard] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [MicroBeard] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [MicroBeard] SET ARITHABORT OFF 
GO
ALTER DATABASE [MicroBeard] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [MicroBeard] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [MicroBeard] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [MicroBeard] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [MicroBeard] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [MicroBeard] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [MicroBeard] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [MicroBeard] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [MicroBeard] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [MicroBeard] SET  ENABLE_BROKER 
GO
ALTER DATABASE [MicroBeard] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [MicroBeard] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [MicroBeard] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [MicroBeard] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [MicroBeard] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [MicroBeard] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [MicroBeard] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [MicroBeard] SET RECOVERY FULL 
GO
ALTER DATABASE [MicroBeard] SET  MULTI_USER 
GO
ALTER DATABASE [MicroBeard] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [MicroBeard] SET DB_CHAINING OFF 
GO
ALTER DATABASE [MicroBeard] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [MicroBeard] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [MicroBeard] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [MicroBeard] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'MicroBeard', N'ON'
GO
ALTER DATABASE [MicroBeard] SET QUERY_STORE = OFF
GO
ALTER DATABASE [MicroBeard] SET  READ_WRITE 
GO
